# Generated by Django 5.2.12 on 2026-03-31 13:45

from django.db import migrations


ACHIEVEMENTS = [
    {
        'key': 'first_login',
        'name': 'Welcome Aboard!',
        'description': 'Logged into LearnHub for the first time',
        'icon': 'RocketIcon',
        'color': '#42a5f5',
        'category': 'general',
        'sort_order': 0,
    },
    {
        'key': 'profile_complete',
        'name': 'Identity Established',
        'description': 'Complete your profile with a bio',
        'icon': 'BadgeIcon',
        'color': '#ab47bc',
        'category': 'general',
        'sort_order': 1,
    },
    {
        'key': 'first_enrollment',
        'name': 'First Steps',
        'description': 'Enrol in your first course',
        'icon': 'SchoolIcon',
        'color': '#66bb6a',
        'category': 'student',
        'sort_order': 2,
    },
    {
        'key': 'three_courses',
        'name': 'Knowledge Seeker',
        'description': 'Enrol in 3 or more courses',
        'icon': 'AutoStoriesIcon',
        'color': '#f57c00',
        'category': 'student',
        'sort_order': 3,
    },
    {
        'key': 'five_courses',
        'name': 'Lifelong Learner',
        'description': 'Enrol in 5 or more courses',
        'icon': 'StarIcon',
        'color': '#ffd54f',
        'category': 'student',
        'sort_order': 4,
    },
    {
        'key': 'course_creator',
        'name': 'Course Creator',
        'description': 'Create your first course',
        'icon': 'AutoStoriesIcon',
        'color': '#66bb6a',
        'category': 'teacher',
        'sort_order': 5,
    },
    {
        'key': 'popular_teacher',
        'name': 'Popular Teacher',
        'description': 'Have 5 or more students enrolled across your courses',
        'icon': 'FavoriteIcon',
        'color': '#ef5350',
        'category': 'teacher',
        'sort_order': 6,
    },
    {
        'key': 'prolific_teacher',
        'name': 'Prolific Educator',
        'description': 'Create 3 or more courses',
        'icon': 'FireIcon',
        'color': '#ff7043',
        'category': 'teacher',
        'sort_order': 7,
    },
    {
        'key': 'explorer',
        'name': 'Explorer',
        'description': 'Browse the course catalogue',
        'icon': 'ViewIcon',
        'color': '#26c6da',
        'category': 'general',
        'sort_order': 8,
    },
    {
        'key': 'community_member',
        'name': 'Community Member',
        'description': 'Be part of the LearnHub community',
        'icon': 'ThumbUpIcon',
        'color': '#ab47bc',
        'category': 'general',
        'sort_order': 9,
    },
    {
        'key': 'first_submission',
        'name': 'Hand It In',
        'description': 'Submit your first assignment',
        'icon': 'AssignmentTurnedInIcon',
        'color': '#26a69a',
        'category': 'student',
        'sort_order': 10,
    },
    {
        'key': 'first_graded',
        'name': 'Marked & Noted',
        'description': 'Receive a grade on an assignment',
        'icon': 'GradingIcon',
        'color': '#7e57c2',
        'category': 'student',
        'sort_order': 11,
    },
]


def seed_achievements(apps, schema_editor):
    AchievementDefinition = apps.get_model('achievements', 'AchievementDefinition')
    for achievement in ACHIEVEMENTS:
        AchievementDefinition.objects.get_or_create(
            key=achievement['key'],
            defaults=achievement,
        )


def remove_achievements(apps, schema_editor):
    AchievementDefinition = apps.get_model('achievements', 'AchievementDefinition')
    keys = [a['key'] for a in ACHIEVEMENTS]
    AchievementDefinition.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_achievements, remove_achievements),
    ]
