# Generated by Django 5.2.12 on 2026-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_assignment_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
